<Project>
  <PropertyGroup>
    <AstralGameRoot Condition="'$(AstralGameRoot)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Astral Party\8vJXnINT</AstralGameRoot>
    <AstralLocalRefsRoot>$(MSBuildThisFileDirectory).work/refs</AstralLocalRefsRoot>
    <AstralBepInExRoot Condition="'$(AstralRefsRoot)' != ''">$(AstralRefsRoot)</AstralBepInExRoot>
    <AstralBepInExRoot Condition="'$(AstralBepInExRoot)' == '' and Exists('$(AstralLocalRefsRoot)/core/BepInEx.Core.dll')">$(AstralLocalRefsRoot)</AstralBepInExRoot>
    <AstralBepInExRoot Condition="'$(AstralBepInExRoot)' == ''">$(AstralGameRoot)/BepInEx</AstralBepInExRoot>
  </PropertyGroup>
</Project>
